language: php
dist: xenial

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 7.2
      env: PREFER_LOWEST=1
    - php: 7.4
      env: LINT=1

before_install:
  - PYTHON3_VERSION=$(pyenv versions | grep -oP "3.[0-9]{1,}.[0-9]{1,}" | tail -1)
  - pyenv global ${PYTHON3_VERSION}

install:
  - if [[ $PREFER_LOWEST != 1 ]]; then travis_retry composer update --no-interaction --prefer-dist; fi
  - if [[ $PREFER_LOWEST == 1 ]]; then travis_retry composer update --no-interaction --prefer-dist --prefer-lowest; fi
  - if [[ $LINT != 1 ]]; then pip3 install cchardet xld_logchecker eac_logchecker; fi

script:
  - if [[ $LINT == 1 ]]; then composer run lint; fi
  - if [[ $LINT == 1 ]]; then composer run static-analysis; fi
  - if [[ $LINT != 1 ]]; then composer run test; fi
  - if [[ $LINT != 1 ]]; then bin/logchecker --version; fi

before_deploy:
  - rm -rf vendor
  - composer install --no-dev --optimize-autoloader
  - php -d phar.readonly=0 bin/compile

deploy:
  provider: releases
  api_key:
    secure: fsMbI9nYrxmSQRXNjNPqd7Oxdnnv5HyKPd2Va7AqQzbOsdTTPY5tz3/6RdeaG2cPjG19qxbWu/g21ysb/hWWeVyFpmIc8pl4TZcJTOrv28VNJiru87ynjjCKbP5N0AD6pnaVs3A6u8zjVZy2vlW1eOXU18xgTgA+yk/IoZX2AChItXdphgVI0rd941d/hkrnMj5shzy1Uv6wgbJSpD27UQ4d3zgGAgc6gteuXGRy0dizo4g0VrvQ21rpezLAgT0e1cefjIqAYwLFP2tm/Nsi5QLLYhSsQptkCUto+gFeGCLBgIMV5dz2IWIkFXQOdiVYjIGmT86GFN32bMLMDpO0ppTc8NPDjnni1cnM6/N/gMm/JvmLzGHMMEGYMgO+Yg1qgQi8MwjTk5twklsiJSUHIsa1WWo1+uj1rO5TQ8CzgajmNr5upJ9PI75rbOw+cn2DzR8UBPVDl+1YxJfz4XhmRgSdF98s+7kGS3Ehaby+gXnH76m2dU43CWukaz9hwGvDdG4nc0C7XDtLq15vbKcK5BywI0pCJRVwa81KBrt9mP4CU1hY2VidS1iQubegJ59bNN/B+xBW92i4AmBd1QhbBnExQ05xFpusIxjSx/7ty9GNTqm3P5JDRQUj+dgNGNgfoaq/ACkWfd68W/IHqPLnh6saReQd2mrTBKtoDs0Atik=
  file: logchecker.phar
  skip_cleanup: true
  on:
    tags: true
    repo: OPSnet/Logchecker
    php: '7.2'
    condition: $PREFER_LOWEST != 1 && $Lint != 1
